### ISSUE TITLE
Super-instructions

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#16]
Literature: look for work by [Anton Ertl](http://www.complang.tuwien.ac.at/projects/interpreters.html) (Forth)

Basic idea: suppose in a runtime (!) execution profile we see that the sequence LOAD_FAST, LOAD_FAST occurs frequently. We can introduce a new opcode, LOAD_FAST_LOAD_FAST (LFLF), and blindly replace the first of every pair of LOAD_FAST opcodes with the super-instruction LFLF. The code then changes from e.g.
```
    LOAD_FAST 0 (x)
    LOAD_FAST 1 (y)
    BINARY_ADD
```
to
```
    LOAD_FAST_LOAD_FAST 0 (x)
    LOAD_FAST 1 (y)
    BINARY_ADD
```

The opcode case for LFLF would do the following:

- load the first variable (x)
- decode the argument for the second opcode
- adjust the program counter to consume the second opcode
- load the second variable(y)
- DISPATCH()

This saves all the other stuff that's done for each opcode (tracing etc.), and it doesn't even read the second opcode. (If the second LOAD_FAST is preceded by an EXTENDED_ARG opcode we should not do the substitution, so that getting the argument for the second opcode is a single byte access and the p-counter update is a fixed add.)

The beauty is that if there's a jump to the second LOAD_FAST instruction, things just work, so this form of code rewriting can be very fast.

**Comment by markshannon** [comment]
This seems to have expired. Let's try to restart it.

First of all, let's narrow this issue down to superinstructions that are inserted into the quickened code, but not are not present in the original code object.

Superinstructions that are inserted by the compiler into the code object are discussed in #36.

We want to exclude from this list:
* Combined instructions (typically a pair where only one instruction has an operand)
* Any pairs when one (or both) of the pair can be specialized
* Any pair including `FOR_ITER`, for now. It is not clear what the best way to speed up `for` loops is.

Which leaves this list of common pairs, compiled from various sources:
* LOAD_FAST LOAD_FAST
* COMPARE_OP POP_JUMP_IF_FALSE
* STORE_FAST LOAD_FAST
* LOAD_FAST LOAD_CONST
* LOAD_CONST COMPARE_OP
* STORE_FAST STORE_FAST
* LOAD_CONST LOAD_FAST

We are not just interested in the prevalence of the pairs, but the profitability of combining them
Of the above the simple pairs (combining LOAD_FAST, STORE_FAST and LOAD_CONST) are worth combining because the dispatch overhead is a significant part of the execution time.
However, COMPARE_OP is a complex instruction, and may benefit from specialization. So well leave that out for now as well.

I am suspicious of the STORE_FAST STORE_FAST pair. I suspect that it shows up a lot in tests, but less so in production code.
I could well be wrong, and would be happy to be proved wrong, but I'm going to leave it out for now.

That leaves just four:
* LOAD_FAST LOAD_FAST
* STORE_FAST LOAD_FAST
* LOAD_FAST LOAD_CONST
* LOAD_CONST LOAD_FAST

It worth noting that none of LOAD_FAST, STORE_FAST and LOAD_CONST can change the state from non-tracing to tracing.
Since tracing is always off when executing quickened instructions, this gives us another advantage. We don't need to check for tracing at the end of the instruction. In fact, we can take advantage of this to quicken LOAD_FAST, STORE_FAST and LOAD_CONST by replacing them with "NO TRACE" versions that do not check for tracing when dispatching.

This gives us three more instructions that might be worth adding:

* LOAD_FAST_NO_TRACE
* LOAD_CONST_NO_TRACE
* STORE_FAST_NO_TRACE

**Comment by gvanrossum** [comment]
So is your conclusion to *just* add the no-trace instructions, or also the four specialization you added?

**Comment by markshannon** [comment]
My conclusion is that we should run some experiments :slightly_smiling_face:

**Comment by markshannon** [comment]
Initial experiments show no speedup with the four super-instructions and ~2% speedup adding `STORE_FAST__STORE_FAST`
That might be a real effect, or just the `unpack_sequence` benchmark.
It is also on my laptop without restrictions on the power management, so noisy.
From this I conclude that more experiments are necessary :slightly_smiling_face: 

If you want to play, the code is here: https://github.com/faster-cpython/cpython/tree/super-instructions

**Comment by JelleZijlstra** [comment]
Could this be handled by a peephole optimization step that simply elides the pair of instructions? I suppose that's only safe if there are no `locals()` calls, and no other references to the variable.

**Comment by zcpara** [comment]
If there are __code__, dir(), __traceback__ calls,  deletion the pair of instructions will also be unsafe.

**Comment by zcpara** [comment]
Is it worth to make a super-instruction for UNPACK_SEQUENCE and its following STORE_FASTs?  In bm_nbody.py of Pyperformance, these patterns are in hot loop bodies. We can identify these patterns in compilation phase. 

def advance(dt, n, bodies=SYSTEM, pairs=PAIRS):
    for i in range(n):
        for (([x1, y1, z1], v1, m1),
             ([x2, y2, z2], v2, m2)) in pairs:

80          14 GET_ITER
        >>   16 FOR_ITER               112 (to 242)
             18 UNPACK_SEQUENCE          2
             20 UNPACK_SEQUENCE          3
             22 UNPACK_SEQUENCE          3
             24 STORE_FAST               5 (x1)
             26 STORE_FAST               6 (y1)
             28 STORE_FAST               7 (z1)
             30 STORE_FAST               8 (v1)
             32 STORE_FAST               9 (m1)

 81          34 UNPACK_SEQUENCE          3
             36 UNPACK_SEQUENCE          3
             38 STORE_FAST              10 (x2)
             40 STORE_FAST              11 (y2)
             42 STORE_FAST              12 (z2)
             44 STORE_FAST              13 (v2)
             46 STORE_FAST              14 (m2)

**Comment by markshannon** [comment]
We don't want to distort our selection of superinstructions, or optimizations in general, to fit the `pyperformance` benchmark suite.

Do we have evidence that `UNPACK_SEQUENCE` followed by a sequence of `STORE_FAST`s is a common pattern?
We now have `STORE_FAST__STORE_FAST` as a superinstruction, which will help with the above patterns.

**Comment by gvanrossum** [comment]
I'd expect that 2 or more STORE_FAST are the most likely thing following UNPACK_SEQUENCE, given the abundance of common patterns like
```
x, y = point
for x, y in points: ...
for k, v in d.items(): ...
for i, x in enumerate(a): ...
for x, y in zip(xs, ys): ...
for root, dirs, files in os.walk(...): ...
```
If you want more evidence we can look through the top 100 packages for such sequences.

From a quick grep of the stdlib, just 2 values is by far the most common.

**Comment by whjpji** [comment]
I have downloaded all the wheels in [the top 100 python packages](https://hugovk.github.io/top-pypi-packages/), and counted the patterns of unpacking sequence.

Here is the result:
| Pattern             | Lines | Percent |
|:--------------------|:------|:-----|
| for x, y in ...     | 5842  | 23.5% |
| x, y = ...          | 13244 | 52.8% |
| for x, y(, z)+ in ...  | 125   |   0.5% |
| x, y(, z)+ = ...       | 5852  | 23.3% |
| total                | 25063 | 100% |

Statistics shows that 2 `STORE_FAST`s are most likely to follow `UNPACK_SEQUENCE` (about 76.2%), but there are still 23.8% of them are 3 or more `STORE_FAST`s that follows an `UNPACK_SEQUENCE`.

**Comment by gvanrossum** [comment]
Thanks, that is very useful!

**Comment by pxeger** [comment]
I've hacked together something of a framework to analyse bytecode and look for patterns like the above, also using the top 100 PyPI packages (or it can be adapted for any other corpus of `pyc` files, really). You may find it helpful: https://github.com/pxeger/pycstats

**Comment by pxeger** [comment]
Results for `UNPACK_SEQUENCE` followed by any two instructions (this is based on the compiled output unweighted by how many times they're executed, so not quite representative):

```
72975 UNPACK_SEQUENCE STORE_FAST STORE_FAST
993 UNPACK_SEQUENCE LOAD_FAST STORE_ATTR
744 UNPACK_SEQUENCE STORE_NAME STORE_NAME
592 UNPACK_SEQUENCE STORE_FAST UNPACK_SEQUENCE
588 UNPACK_SEQUENCE STORE_FAST LOAD_FAST
287 UNPACK_SEQUENCE LOAD_FAST LOAD_CONST
280 UNPACK_SEQUENCE STORE_DEREF STORE_FAST
256 UNPACK_SEQUENCE STORE_DEREF STORE_DEREF
236 UNPACK_SEQUENCE STORE_FAST STORE_DEREF
219 UNPACK_SEQUENCE UNPACK_SEQUENCE STORE_FAST
162 UNPACK_SEQUENCE STORE_FAST LOAD_GLOBAL
55 UNPACK_SEQUENCE LOAD_FAST LOAD_FAST
52 UNPACK_SEQUENCE LOAD_DEREF STORE_ATTR
51 UNPACK_SEQUENCE LOAD_FAST LOAD_ATTR
50 UNPACK_SEQUENCE STORE_FAST POP_BLOCK
20 UNPACK_SEQUENCE STORE_FAST LOAD_DEREF
20 UNPACK_SEQUENCE STORE_FAST JUMP_FORWARD
19 UNPACK_SEQUENCE STORE_FAST LOAD_CONST
18 UNPACK_SEQUENCE STORE_GLOBAL STORE_GLOBAL
16 UNPACK_SEQUENCE LOAD_DEREF LOAD_ATTR
10 UNPACK_SEQUENCE LOAD_GLOBAL STORE_ATTR
8 UNPACK_SEQUENCE LOAD_GLOBAL LOAD_CONST
7 UNPACK_SEQUENCE STORE_FAST SETUP_FINALLY
5 UNPACK_SEQUENCE LOAD_NAME STORE_ATTR
4 UNPACK_SEQUENCE STORE_NAME UNPACK_SEQUENCE
4 UNPACK_SEQUENCE STORE_GLOBAL STORE_FAST
4 UNPACK_SEQUENCE STORE_FAST JUMP_ABSOLUTE
3 UNPACK_SEQUENCE STORE_DEREF UNPACK_SEQUENCE
3 UNPACK_SEQUENCE STORE_FAST UNPACK_EX
3 UNPACK_SEQUENCE UNPACK_SEQUENCE STORE_DEREF
3 UNPACK_SEQUENCE UNPACK_SEQUENCE UNPACK_SEQUENCE
2 UNPACK_SEQUENCE STORE_DEREF LOAD_DEREF
1 UNPACK_SEQUENCE LOAD_GLOBAL LOAD_ATTR
1 UNPACK_SEQUENCE EXTENDED_ARG STORE_NAME
1 UNPACK_SEQUENCE EXTENDED_ARG UNPACK_EX
```

**Comment by gvanrossum** [comment]
One percent overall improvement is nothing to sneeze at! Please submit a PR. (Sorry for the slow response!)

**Comment by ssweber** [comment]
“1.006x faster“ - that’s 0.6% correct?

**Comment by gvanrossum** [comment]
Um, yeah, I misread. Still.

**Comment by zcpara** [comment]
Update the performance data with the latest code base. It's [1.008x faster](https://gist.github.com/zcpara/2a1fdaa496adc7fda727020325eb8d16).

https://bugs.python.org/issue45260
https://github.com/python/cpython/pull/28519

**Comment by gvanrossum** [comment]
I think this can be closed now the code generator supports defining super-instructions.
