### ISSUE TITLE
Reduce strength of certain integer operations on constants

### ISSUE THREAD

**Issue by lpereira** [faster-cpython/ideas#232]
As part of #231, I do believe that specializing certain integer operation on constants, such as:

- Division, multiplication, or mod by a power of two
- Division by a constant (maybe use something like [libdivide](https://libdivide.com/)?)

Will have a measurable impact on performance.

**Comment by pxeger** [comment]
I wonder what impact this would have on the division by ten which was [brought up on python-dev recently](https://mail.python.org/archives/list/python-dev@python.org/thread/ZICIMX5VFCX4IOFH5NUPVHCUJCQ4Q7QM/#VDII5EBMXLNO4U3BSSNWAW2ETLNG6YUN), and any potential similar optimisations the compiler decides to do.

**Comment by lpereira** [comment]
> I wonder what impact this would have on the division by ten which was [brought up on python-dev recently](https://mail.python.org/archives/list/python-dev@python.org/thread/ZICIMX5VFCX4IOFH5NUPVHCUJCQ4Q7QM/#VDII5EBMXLNO4U3BSSNWAW2ETLNG6YUN), and any potential similar optimisations the compiler decides to do.

It is my understanding that, once #231 is finished, this would provide us with similar performance gains.

**Comment by FreddieWitherden** [comment]
So a couple of points to consider.  Firstly, on recent hardware integer multiplications are very fast with latencies as low as three cycles.  For an interpreted language — where you have a relatively large amount of work going on between instructions — the difference between one and three cycles is essentially a rounding error (one cycle coming from the use of a shift instead of a mul).

Division is another matter.  Historically divide has been a slow operation.  However, the situation is changing.  The Apple M1 can push through divisions within a factor of 2x of libdivide (but without any need for pre-computation or additional state).  Here, the additional I and D cache pressure from libdivide is likely to outweigh the benefit.

**Comment by markshannon** [comment]
The overhead of boxing, reference count manipulation and interpreter dispatch is the dominant factor, even for integer division.

If we can get rid of all of those, it is reasonable to assume that a heavyweight top tier optimizer (e.g. LLVM) will perform this optimization for us. For lower tier optimizers, the additional complexity just isn't worth it.
