### ISSUE TITLE
Handle boxing of cell variables in the bytecode.

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#41]
This is a refinement of #37, and occurred to me when discussing https://bugs.python.org/issue43693
Rather than simply tacking the cells on to the end of locals, why not interleave them?
Arguments that escape could then be left in their "natural" position.
Doing so would simplify frame creation code a lot, as it wouldn't need to know about cell variables at all.

Example:
```python
def f(a):
    def g():
           return a
    return g
```
When creating the frame for `f`, frame creation code (e.g. `_PyEval_MakeFrameVector`) has to know about cell variables, free variables and which cell variables are arguments. That could all be handled in the compiler.

Currently the bytecode for `f` above is:
```
  2           0 LOAD_CLOSURE             0 (a)
              2 BUILD_TUPLE              1
              4 LOAD_CONST               1 (<code object g at 0x7f8075837c60, file "<stdin>", line 2>)
              6 LOAD_CONST               2 ('f.<locals>.g')
              8 MAKE_FUNCTION            8 (closure)
             10 STORE_FAST               1 (g)

  4          12 LOAD_FAST                1 (g)
             14 RETURN_VALUE
```
The compiler knows that `a` escapes `f`, so why not use that knowledge?
By boxing `a` in the bytecode, closures and normal functions can be treated the same at runtime. 
We only need to add one extra instruction in this case:
```
  2           0 MAKE_CELL                0 (a)
              2 LOAD_CLOSURE             0 (a)
              4 BUILD_TUPLE              1
              6 LOAD_CONST               1 (<code object g at 0x7f8075837c60, file "<stdin>", line 2>)
              8 LOAD_CONST               2 ('f.<locals>.g')
             10 MAKE_FUNCTION            8 (closure)
             12 STORE_FAST               1 (g)

  4          12 LOAD_FAST                1 (g)
             14 RETURN_VALUE
```
(The code for `g` is unchanged)

**Comment by ncoghlan** [comment]
@ericsnowcurrently Could you take a look at the draft PEP 558 (defined semantics for locals) implementation and see how this affects that? If the cell creation is in the byte code, what happens if the frame's C API is accessed before the cells are created?

(I'm sure any problems will be solvable, I just wanted to ensure the potential interaction was on your radar)

**Comment by gvanrossum** [comment]
Presumably the code just has to check for cells and deter them
properly...--
--Guido (mobile)

**Comment by ericsnowcurrently** [comment]
@ncoghlan, I took a look and I don't see anything that would be a problem.

WIth MAKE_CELL, the corresponding fastlocals offset will be set to NULL (or an arg value) until the MAKE_CELL opcode is executed, instead of always holding a cell (which is similarly set to NULL or an arg value).  `map_to_dict()` (in frameobject.c) already accommodates the new way, so everything else should be fine.

(I didn't see anywhere else in your branch where we make the assumption that the fastlocals offset for a cell var always holds a cell object.)

**Comment by ericsnowcurrently** [comment]
The yak is now mostly shaved:

* (merged) python/cpython#26364
* python/cpython#26375
* python/cpython#26388
* python/cpython#25152
* python/cpython#26396 (actually add `MAKE_CELL` and interleave the locals/cells)

**Comment by ericsnowcurrently** [comment]
The main objective here is done but there are still some related work items left open:

* properly interleaving the cells with the locals in their "natural" order
* tracking order/kinds deeper in the compiler rather than computing it during the assembler step
* tracking arg kinds in `localspluskinds`

We should consider if any of these are worth prioritizing.

**Comment by ericsnowcurrently** [comment]
I've created a "To do" note on the [project board](https://github.com/faster-cpython/ideas/projects/1) to cover those items.

**Comment by gvanrossum** [comment]
On Thu, Jun 17, 2021 at 11:40 Eric Snow ***@***.***> wrote:

> I've created a "To do" note on the project board
> <https://github.com/faster-cpython/ideas/projects/1> to cover those items.
>

Hm, an open issue seems more appropriate here? Maybe even an open bpo
issue?

> --
--Guido (mobile)

**Comment by ericsnowcurrently** [comment]
> Hm, an open issue seems more appropriate here? Maybe even an open bpo issue?

Agreed.  I left https://bugs.python.org/issue43693 open to address [those things](https://bugs.python.org/issue43693#msg396015).
