### ISSUE TITLE
Update the class's `tp_version_tag` when the cached keys changes.

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#525]
During attribute lookup we often need to know that shadowing isn't happening; either instance attributes shadowing class attributes, or vice versa.

To do that we check the type version and the dict keys version.

For the most common case of loading an attribute from the instance, this isn't a problem as we don't need to worry about the instance shadowing the class, but when looking up an object on the class, we have to pay for the extra check.

If we change the type version whenever the cached keys changes, then we wouldn't need to check both, just the type version.
This reduces the number of memory reads to perform the checks from 7 to 3, and the length of dependent load chain from 3 to 2.

The class dictionary cannot be modified directly, so there shouldn't be any problem with the version and keys getting out of sync.

With this change the code for `LOAD_ATTR_METHOD_WITH_VALUES` can be reduced from 
```C
    PyObject *self = TOP();
    PyTypeObject *self_cls = Py_TYPE(self);
    _PyLoadMethodCache *cache = (_PyLoadMethodCache *)next_instr;
    uint32_t type_version = read_u32(cache->type_version);
    DEOPT_IF(self_cls->tp_version_tag != type_version, LOAD_ATTR);
    PyDictOrValues dorv = *_PyObject_DictOrValuesPointer(self);
    DEOPT_IF(!_PyDictOrValues_IsValues(dorv), LOAD_ATTR);
    PyHeapTypeObject *self_heap_type = (PyHeapTypeObject *)self_cls;
    DEOPT_IF(self_heap_type->ht_cached_keys->dk_version !=
             read_u32(cache->keys_version), LOAD_ATTR);
    PyObject *res = read_obj(cache->descr);
    SET_TOP(Py_NewRef(res));
    PUSH(self);
```
to
```C
    PyObject *self = TOP();
    PyTypeObject *self_cls = Py_TYPE(self);
    _PyLoadMethodCache *cache = (_PyLoadMethodCache *)next_instr;
    uint32_t type_version = read_u32(cache->type_version);
    DEOPT_IF(self_cls->tp_version_tag != type_version, LOAD_ATTR);
    PyDictOrValues dorv = *_PyObject_DictOrValuesPointer(self);
    DEOPT_IF(!_PyDictOrValues_IsValues(dorv), LOAD_ATTR);
    PyObject *res = read_obj(cache->descr);
    SET_TOP(Py_NewRef(res));
    PUSH(self);
```
This might not look like much of a saving, but the
`DEOPT_IF(self_heap_type->ht_cached_keys->dk_version != read_u32(cache->keys_version), LOAD_ATTR);`
statement is expensive and similar improvements can be made to a few other instructions.

**Comment by Fidget-Spinner** [comment]
We should also update the class's `tp_version_tag` when the dict/values pointer updates to another form. The current code is littered with `DEOPT_IF(!_PyDictOrValues_IsValues(dorv), LOAD_ATTR);` That would cut things down to a single `DEOPT_IF`..

**Comment by brandtbucher** [comment]
> We should also update the class's `tp_version_tag` when the dict/values pointer updates to another form.

But wouldn't that mean that classes with instances that are prone to `__dict__` materialization will see tons of version updates (since every new instance invalidates the `tp_version_tag` at some point)?

**Comment by Fidget-Spinner** [comment]
> > We should also update the class's `tp_version_tag` when the dict/values pointer updates to another form.
> 
> But wouldn't that mean that classes with instances that are prone to `__dict__` materialization will see tons of version updates (since every new instance invalidates the `tp_version_tag` at some point)?

Oh right. Sorry I misunderstood when the dict_or_values field materialises. (Had the wrong impression it belonged to the class instead of the object).

**Comment by jbower-fb** [comment]
As I think @carljm/@dinov mentioned elsewhere, we're interested in this optimization for Cinder too. I've had a play and want to share results so far. Things aren't perfect so I'm interested to hear any thoughts on possible improvements.

My current implementation is here: https://github.com/jbower-fb/cpython-jbowerfb/tree/loadattropts

Unfortunately, it looks like just bumping the type version with the keys version isn't always possible. There are cases where the keys can escape and become detached from the type. For example, on dict materialization [here](https://github.com/python/cpython/blob/main/Objects/dictobject.c#L5448) we end up sharing keys with the new dict. This can then escape via `__dict__` and there's no way to tie key changes back to the type.

To work around this I've limited specialization to only types with all instances using inline-values rather than a dict. For this I've added a new type flag which gets set whenever we convert any instance's attribute storage from inline-values to a dict. I also bump the type version on this event so overall we're able avoid and invalidate any types for which some instances don't use inline-values.

This change made things functional but overall PyPerformance showed a regression of ~1.01x - 1.02x. It looks like most of the overhead came from bumping the type version via `PyType_Modified` in `_PyObject_StoreInstanceAttribute`. I was able to neutralize this by adding `PyType_ModifiedNonRecursive`. I think this is valid, and I added an assert to confirm derived types don't share keys with their parents. Let me know if I missed something though. We may also consider this a change in behavior for type-watchers and need to document it.

Although, the results are just perf neutral, this still might be a useful change. This approach should allow shorter instruction sequences for micro-opcodes/JIT. It also gets rid of 2 of the 3 deopts in `LOAD_ATTR_METHOD_WITH_VALUES ` instead of just 1.

From here I'm looking for comments. Are shorter instruction sequences later worth taking up a type-flag bit now? Can anyone think of another way around the escaping issue? Maybe a way of tracking and switching away from shared keys if the dict is further modified?

Also, I haven't done any profiling/stats collection around when the dict materialization events occur. I'd welcome any comments on where might be best to focus for to improve things.

**Comment by markshannon** [comment]
@jbower-fb 
Thanks for investigating this.

Dictionary keys escaping control of the class does seem to be a problem.
I'm inclined to leave things as they are.

I think there is a way to save one `DEOPT_IF` check, but I doubt it is worth it:

We are using the dictionary keys as a proxy for "is the named attribute *not* present in the instance's `__dict__`".
The attribute can only be shadowed if the object `__dict__` has been materialized, or that attribute has been set directly on the object.

By adding an `expected_dict_keys_version` field to the class, we can check when setting the instance attribute that the expected version on the class and the actual version on the dict keys match. If they do not match, then we can update the class's version number.

We would still need to check that the instance's `__dict__` had not be materialized, so we only save one `DEOPT_IF` check.

**Comment by brandtbucher** [comment]
> By adding an `expected_dict_keys_version` field to the class, we can check when setting the instance attribute that the expected version on the class and the actual version on the dict keys match. If they do not match, then we can update the class's version number.

Wouldn't `ht->expected_dict_keys_version` just be the same as `ht->ht_cached_keys->dk_version`?

I haven't checked, but I thought that key-sharing still happens as long as possible when `__dict__`s are materialized. If so, checking this would be as simple as `__dict__->ma_keys == ht->ht_cached_keys`, right?

**Comment by jbower-fb** [comment]
If we're interested in just eliminating the deopt on dict materialization we can do that by bumping the type version whenever that occurs. I already have the code for that and it doesn't need a new type flag. Let me see if I can get that to pass the Python test suite and then check the perf. It may happen infrequently enough to not need the non-recurisve version of `PyType_Modified()`.

**Comment by jbower-fb** [comment]
Also, it occurs to me that if the biggest concern with the implementation I already had is the new type flag we could maybe hijack the top-bit of `tp_version_tag` instead?

**Comment by brandtbucher** [comment]
> If we're interested in just eliminating the deopt on dict materialization we can do that by bumping the type version whenever materialization occurs.

I would assume that, for a given type, `__dict__` materialization isn't something that ever happens "a few" times. Rather, it probably either never happens, or happens *a lot*. It would seem that in the latter case, there would be constant cache invalidation and lots of wasted versions.

**Comment by jbower-fb** [comment]
That must be the case because overall it does show a bit of a slow-down on pyperformance (1.01x). I guess there needs to be something sticky like a type-flag so once an instance materializes a dict the type doesn't bother to specialize again.

So, any opinions on using a bit in `tp_version_tag`?
