### ISSUE TITLE
fyi - started a discourse discussion about contributing the Pyston jit

### ISSUE THREAD

**Issue by kmod** [faster-cpython/ideas#554]
Hello all, I started a [discourse topic](https://discuss.python.org/t/contributing-the-pyston-jit/24195) about the idea of contributing our Pyston jit to cpython main and I thought the people here might be interested

**Comment by gvanrossum** [comment]
I don't know if you'll get a straight reply, but it looks unlikely since it's a lot of code to maintain, with no core devs who understand it. This makes it a risk of becoming a white elephant. Also the faster-cpython group is pursuing a different architecture. I think if you wanted to come to the Language Summit at PyCon (Wed April 19 in Salt Lake City) we'd be happy to add a discussion about this to the agenda (though I'm not an organizer so I can't make a hard promise). If you're interested in that and can't find the invitation let me know and I'll dig it up.

**Comment by markshannon** [comment]
The discussion is taking place on discourse, and maybe at the language summit, so no need to keep this open.
