### ISSUE TITLE
Make the IR of the interpreter generator(s) a list of micro-ops, and nothing else.

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#617]
Currently, the tier1 and tier2 interpreter code generators do quite a lot of special casing and some analysis.
By making the IR more uniform, the need for that analysis can be largely removed.

For example, the tier 1 back end needs to know how long an instruction is, and its cache formats.
That analysis should be the job of the front-end, and the `bytecodes.c` specification.

Let's take a very simple example, `LOAD_FAST`.

`LOAD_FAST` is an instruction, which means it needs to be treated differently from a macro.
It has an implicit store of the IP at the start, and the code generator needs to compute the length of the instruction, instead of it being explicit in the code.

Suppose the front-end transformed
```
inst(LOAD_FAST, (-- value)) {
            value = GETLOCAL(oparg);
            assert(value != NULL);
            Py_INCREF(value);
        }
```
into:
```
op(_LOAD_FAST, (-- value)) {
            value = GETLOCAL(oparg);
            assert(value != NULL);
            Py_INCREF(value);
        }
macro(LOAD_FAST) = SAVE_IP + _LOAD_FAST + INCREMENT_IP(operand = 1);
```
Only `macro`s need to be handled, there are no `inst`s in the IR.
The code generator doesn't need to know about instruction length or modifications to the IP as they are explicit.

**Comment by gvanrossum** [comment]
Yeah, this has been bothering me a lot too.

**Comment by markshannon** [comment]
I'd like to bump this up the priority list. Our handling of the instruction pointer in tier 2 is a bit untidy and I think doing this would help tidy it up.

**Comment by gvanrossum** [comment]
Having pondered more, I'd like to push back on this.

I think adding the SAVE_IP explicitly to the start of the macro is just adding noise, since it would be the first uop of every single macro expansion. Adding it "implicitly" in the translator whenever it starts translating the next instruction is fine.

Note that the translation table *already* has a uniform format regardless of whether the source uses `inst` or `op`.

@markshannon, if there are specific parts of the code generator (Python code in Tools/cases_generator/) or the translator (in Python/optimizer.c) or the Tier 2 interpreter (in Python/executor.) that you'd like me to explain or change, don't hesitate to ask. Please link to (or copy fragments of) the code that's confusing you.

**Comment by markshannon** [comment]
Adding `SAVE_CURRENT_IP` doesn't add noise, it makes the implicit explicit. The list of uop is an IR. It should be information rich and verbose. Extra information is good.

Another reason to make `SAVE_CURRENT_IP` (or whatever it ends up being named) is that some instructions do not need to save the instruction pointer at the start. For example `ENTER_EXECUTOR` relies on the executor to execute the instruction it replaces, so it does not need to save the IP, in fact it is possible in future that saving it would be an error.

**Comment by gvanrossum** [comment]
See https://github.com/python/cpython/issues/109287.

Note that in the context of this issue, "IR" refers to the code generator's internal representation of its instructions, which takes the form of multiple data structures in the `Analyzer` class, notably `everything`, `instrs`, `macros`, and others. (I'm calling this out because I never realized this -- I assumed that "IR" referred to the Tier 2 opcode/oparg/operand 3-tuples, which are also referred to as "IR".)

**Comment by gvanrossum** [comment]
@markshannon Is there more you'd like to do here?

**Comment by markshannon** [comment]
Yes, the namespaces of instructions and micro-ops are still mixed, which means that we have data for instructions in the `_PyOpcode_opcode_metadata` table, and data for micro-ops in `_PyOpcode_macro_expansion`.
For example, the `opcode_macro_expansion` for `LOAD_FAST` is `{ .nuops = 1, .uops = { { LOAD_FAST, 0, 0 } } }` which is a bit confusing.

Mixing the two also wastes space.
It also requires a bit of mental juggling to know whether `LOAD_FAST` refers to the tier 1 instruction, or the tier 2 uop.

Instructions and uops should be quite distinct.
We should be able to start both the instruction and uop values at 0, because they would be in different namespaces.

**Comment by gvanrossum** [comment]
Okay, that makes sense.

The easiest way forward then would be to name the auto-synthesized uop names with a leading underscore, e.g. Tier 1 `LOAD_FAST` corresponds to Tier 2 `_LOAD_FAST`. (I've already made it so that all manually-defined uops by convention start with `_`.)

IIRC if we were to do this (you tried it before) we'd run into 1-2 naming conflicts. We can solve those with explicit macro definitions.

**Comment by gvanrossum** [comment]
I am hoping that @iritkatriel can tackle this project?

**Comment by gvanrossum** [comment]
I feel this is done now.
